version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7742:8080"
    restart: unless-stopped
  client:
    build: ./client
    ports:
      - "7741:80"
    restart: unless-stopped
    depends_on:
      - server
